### ISSUE TITLE
Recover from lost zigbee connection

### ISSUE THREAD

**Issue by oleo65** [stanvn/zigbee-plant-sensor#7]
I have deployed 6 zigbee sensor around the house for a week now. In general they work quite reliably and the coverage is a lot better than the BLE variant. 

I do experience a strange connection issue with some of the sensors. They seem to drop out of the zigbee network randomly after >24h of operation and stay stuck there.

* The sensor report in HA as `unavailable`
* The red led on the PCB is constantly `on`. (The same as during the initial connection after reboot, which takes usually between 5-10 seconds). I suspect the led staying on will drain the batteries quite quickly.

After rebooting the sensor (by shorting RST to GND), the sensor always connects back to the network just fine within a few seconds and works again for at least 24 hours without any problems. 

Does anyone else experience any drop outs from zigbee or a similar behaviour?

A first mitigation might be to simly software reset the device if no zigbee connection can be made for say 15-20 minutes. Maybe it is some issue with the Zephyr zigbee stack? I just have no real idea how to implement this yet.

Also I would suggest that we might change the led behaviour from constant on to flashing or even multi-flashing to signal what might be the issue and preserving some precious power.

**Comment by stanvn** [comment]
My sensor are running for a few weeks now without any problem, however I think I found the issue and added some improvements to the main. I think the problem was that I did not let the `zigbee_default_signal_handler` function handle the leave network signal. In other words, the stack did not try to reconnect when device got disconnected from the network. 

I also added some extra led indications. If your problem still exists we might get a bit more information from the led. 

Please let me know if this solves you issue or not.

**Comment by oleo65** [comment]
Thanks for your feedback and code changes. I just flashed some of my sensors with the updated firmware and will observe the behaviour over the next couple of days and report back here. 😃

**Comment by oleo65** [comment]
Your fix seemed to do the trick, thanks a lot. Since then no more connection drop outs. Closing this as resolved.
